### ISSUE TITLE
Transfert data to external influxDB

### ISSUE THREAD

**Issue by admmtkalbertig** [zottelbeyer/QNAP-collectdinfluxdbgrafana#9]
Hello guys,
I have a question.
I would like to send data collected by collectd in another influx DB (OMD-lab).
Is there a way to connect the network created in the dockers to my network and sending data to external influx DB?
I've changed:
<Plugin network>
	Server "127.0.0.1" "25826"
</Plugin>

in
<Plugin network>
	Server "my server" "25826"
</Plugin>

but network configured in the dockers (172.29.0.1) can't comunicate to my network (192.168.1.X).

Looking forward to your reply.
Regards.
Giacomo.

**Comment by zottelbeyer** [comment]
hi Giacomo,

The default docker-compose.yml uses "network_mode: host" which means collectd is running on the same IP as your NAS.
I'm using this exact configuration to send collectd data to influxdb running on another host.

Be aware that dns might not work as expected in the collectd container so you might want to use the IP instead of the hostname (or do some further configuration). Also be aware that there might be firewalls active on either side of collectd/influxdb

If you want to do some debugging attach to the docker container like this:
`docker exec -it qnap-collectd /bin/bash`

try figuring out the network configuration using `ip addr show` and try pinging your target host.

I will not go into the depths of docker network configuration here because there are several good websites doing so, but I will tell you it does work. hope that helps

**Comment by admmtkalbertig** [comment]
Thank you very much zottelbeyer, I will try.

G.

**Comment by zottelbeyer** [comment]
closing for lack of user feedback. Please reopen if you still need help with this.
